language: scala
sudo: false
script:
- sbt test
jdk: oraclejdk9
script:
- java -version
- wget https://raw.githubusercontent.com/paulp/sbt-extras/7e0418fa6520623f17941061f3ab07f7b2ef4f8f/sbt && chmod +x ./sbt
- ./sbt scalafmt::test test
